@startuml

interface State{
    +doAction(Context context): void
}


class StartState implements State{
    +doAction(Context context) : void
}
class StopState implements State{
    +doAction(Context context): void
}

note bottom of StopState
    Uses <b>context</b> var  to set self into
    <b>state</b> field of
    the <b>context</b> object
end note

class Context{
    -state : State
    +getState(): State
    +setState(State newState) : void
}


StartState  *--  Context
StopState *-- Context


@enduml