@startuml
'https://plantuml.com/class-diagram

class LazyLoadSingleton{
    -LazyLoadSingleton()
    -{static} Holder

+{static} getInstance(): LazyLoadSingleton

}

class Holder {
-{static}  INSTANCE :LazyLoadSingleton
}


LazyLoadSingleton *-- Holder
@enduml