@startuml
'https://plantuml.com/class-diagram

class Salad{

    -ingridientMandatory : String
    -ingridientOptional : String
    +{static} Builder
    -Salad(b: Builder)
}




class Builder{
    -ingridientMandatory : String
    -ingridientOptional : String
    +Builder(ingridientMandatory: String)
    +withOptionalIngridient(newOptional : String)
    +build(): Salad
}

note left of  Builder
    <b>ingridientOptional</b> initialized
    with default value
end note


Salad *-- Builder :owns

note right of Salad
    Entity holds the private constructor
    which is used by builder to create an entity
end note
@enduml